### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by janorn** [AtomLinter/linter-js-yaml#16]
I just updated my linter package to 1.11.2.
Atom 1.2.0
linter-js-yaml 1.2.0

Running on OS X 10.9.5

```
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432:29)
    at Object.module.exports.Helpers.rangeFromLineNumber (/Users/atomuser/.atom/packages/linter-js-yaml/node_modules/atom-linter/lib/helpers.coffee:65:43)
    at processMessage (/Users/atomuser/.atom/packages/linter-js-yaml/lib/linter-js-yaml.js:52:27)
    at Object.lint (/Users/atomuser/.atom/packages/linter-js-yaml/lib/linter-js-yaml.js:65:25)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/atomuser/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/atomuser/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/atomuser/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/atomuser/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/atomuser/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/atomuser/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by Arcanemagus** [comment]
@Adezandee if you update `atom-linter` to `^3.3.4` or higher this should be fixed.

**Comment by Adezandee** [comment]
@Arcanemagus Thanks for the hint, done and published v1.2.1

**Comment by Arcanemagus** [comment]
No problem :wink:.

**Comment by janorn** [comment]
v1.2.1 does not solve this. I can confirm that atom-linter 3.3.5 is installed.

**Comment by janorn** [comment]
I have linter-puppet-lint package installed which has an older version installed 3.3.0. Could this cause issues for this module?

**Comment by Arcanemagus** [comment]
What is the exact stack trace of the error now? That will tell us where the helper module is getting loaded from at least.

**Comment by janorn** [comment]
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:432:29)
    at Object.module.exports.Helpers.rangeFromLineNumber (/Users/atomuser/.atom/packages/linter-js-yaml/node_modules/atom-linter/lib/helpers.coffee:67:37)
    at processMessage (/Users/atomuser/.atom/packages/linter-js-yaml/lib/linter-js-yaml.js:52:27)
    at Object.lint (/Users/atomuser/.atom/packages/linter-js-yaml/lib/linter-js-yaml.js:65:25)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/atomuser/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/atomuser/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/atomuser/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/atomuser/.atom/packages/linter/lib/linter.coffee:98:16
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Users/atomuser/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/atomuser/.atom/packages/linter/lib/helpers.coffee:23:18

**Comment by janorn** [comment]
```
/Users/atomuser/.atom/packages (11)
├── auto-encoding-for-ruby@1.0.4
├── hiera-eyaml@0.6.1
├── isotope-ui@2.7.0
├── language-puppet@0.15.0
├── linter@1.11.2
├── linter-erb@0.1.1
├── linter-js-yaml@1.2.1
├── linter-puppet-lint@0.6.1
├── linter-puppet-parse@0.6.0
├── sort-lines@0.12.0
└── xml-formatter@0.9.1
```

**Comment by Arcanemagus** [comment]
Do you have an example file that triggers this? @steelbrain attempted to work around an Atom bug in 3.3.5, but it looks like it didn't quite work so we'll have to see if there is another way around this bug.

**Comment by janorn** [comment]
Try to add a new line in the end of this sample.

```
key:
  subkey: "Value"
key2:     "Another value"
```

**Comment by Arcanemagus** [comment]
Hmmm, doesn't trigger for me, we'll see if it triggers for @steelbrain when he has a chance to look at this.

**Comment by Arcanemagus** [comment]
Just as a sanity check, what is the output of `npm list` from within the linter-js-yaml folder?

**Comment by janorn** [comment]
```
$ npm list
linter-js-yaml@1.2.1 /Users/atomuser/.atom/packages/linter-js-yaml
├─┬ atom-linter@3.3.5
│ ├─┬ tmp@0.0.28
│ │ └── os-tmpdir@1.0.1
│ └── xregexp@2.0.0
├── atom-package-deps@3.0.2
└─┬ js-yaml@3.4.3
  ├─┬ argparse@1.0.3
  │ ├── lodash@3.10.1
  │ └── sprintf-js@1.0.3
  └── esprima@2.7.0
```

**Comment by Arcanemagus** [comment]
Strange, that matches my installations perfectly but I can't reproduce this on Windows or Ubuntu.

**Comment by janorn** [comment]
When you add the new key don't put a : after it. Then the error happens. On my system this is usually so fast so I never have the chance to type a new key with the : before it triggers the error.

**Comment by Arcanemagus** [comment]
Whoops, forgot to update this issue. @Adezandee v3.3.6 of `atom-linter` adds a few more checks for valid ranges before attempting to call the Atom function that is crashing here, do you want to push out an update that includes that or should I?

**Comment by Arcanemagus** [comment]
@janorn your steps to reproduce were missing the "add a key" part :wink:, I can reproduce when trying to add a key so I'll verify v3.3.6 fixes this.

**Comment by Arcanemagus** [comment]
Looks like we missed adding a check that the lineNumber isn't past the end of the document...

**Comment by Arcanemagus** [comment]
Okay, `atom-linter` 3.3.7 is out that will throw an error when you attempt to get a range for a line that is past the end of the buffer, the issue is that this package needs to call that function with 0 based numbers. I'm writing a PR for that now.

**Comment by Arcanemagus** [comment]
v1.2.2 should fix this for you, sorry it took so long to get this fixed for real!

**Comment by Arcanemagus** [comment]
Turns out this error is due to a bug in the linter itself, it's attempting to report a message on a line that doesn't exist: https://github.com/nodeca/js-yaml/issues/218

"Fixing" this actually broke real messages, so I'll be reverting that change and putting in a workaround for that bug in here.
